---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HalBoy::Client
name: HalBoy-Client
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.10.0
version: 0.501
